eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.88.131
    port: 5672
  datasource:
     name: dev
     url: jdbc:mysql://192.168.88.131:3306/snailmall
     username: root
     password: 123456
redis:
    host: 192.168.88.131
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
zk:
  host: 192.168.88.131
